// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsContext(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsContext(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsContext(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashContext(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashContext(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashContext(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContext: Hashable {
  var app: NativeContextApp? = nil
  var device: NativeContextDevice? = nil
  var library: NativeContextLibrary? = nil
  var locale: String? = nil
  var network: NativeContextNetwork? = nil
  var os: NativeContextOS? = nil
  var screen: NativeContextScreen? = nil
  var timezone: String? = nil
  var userAgent: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContext? {
    let app: NativeContextApp? = nilOrValue(pigeonVar_list[0])
    let device: NativeContextDevice? = nilOrValue(pigeonVar_list[1])
    let library: NativeContextLibrary? = nilOrValue(pigeonVar_list[2])
    let locale: String? = nilOrValue(pigeonVar_list[3])
    let network: NativeContextNetwork? = nilOrValue(pigeonVar_list[4])
    let os: NativeContextOS? = nilOrValue(pigeonVar_list[5])
    let screen: NativeContextScreen? = nilOrValue(pigeonVar_list[6])
    let timezone: String? = nilOrValue(pigeonVar_list[7])
    let userAgent: String? = nilOrValue(pigeonVar_list[8])

    return NativeContext(
      app: app,
      device: device,
      library: library,
      locale: locale,
      network: network,
      os: os,
      screen: screen,
      timezone: timezone,
      userAgent: userAgent
    )
  }
  func toList() -> [Any?] {
    return [
      app,
      device,
      library,
      locale,
      network,
      os,
      screen,
      timezone,
      userAgent,
    ]
  }
  static func == (lhs: NativeContext, rhs: NativeContext) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextApp: Hashable {
  var build: String? = nil
  var name: String? = nil
  var namespace: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextApp? {
    let build: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let namespace: String? = nilOrValue(pigeonVar_list[2])
    let version: String? = nilOrValue(pigeonVar_list[3])

    return NativeContextApp(
      build: build,
      name: name,
      namespace: namespace,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      build,
      name,
      namespace,
      version,
    ]
  }
  static func == (lhs: NativeContextApp, rhs: NativeContextApp) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextDevice: Hashable {
  var id: String? = nil
  var manufacturer: String? = nil
  var model: String? = nil
  var name: String? = nil
  var type: String? = nil
  var adTrackingEnabled: Bool? = nil
  var advertisingId: String? = nil
  var trackingStatus: String? = nil
  var token: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextDevice? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let manufacturer: String? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])
    let name: String? = nilOrValue(pigeonVar_list[3])
    let type: String? = nilOrValue(pigeonVar_list[4])
    let adTrackingEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let advertisingId: String? = nilOrValue(pigeonVar_list[6])
    let trackingStatus: String? = nilOrValue(pigeonVar_list[7])
    let token: String? = nilOrValue(pigeonVar_list[8])

    return NativeContextDevice(
      id: id,
      manufacturer: manufacturer,
      model: model,
      name: name,
      type: type,
      adTrackingEnabled: adTrackingEnabled,
      advertisingId: advertisingId,
      trackingStatus: trackingStatus,
      token: token
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      manufacturer,
      model,
      name,
      type,
      adTrackingEnabled,
      advertisingId,
      trackingStatus,
      token,
    ]
  }
  static func == (lhs: NativeContextDevice, rhs: NativeContextDevice) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextLibrary: Hashable {
  var name: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextLibrary? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let version: String? = nilOrValue(pigeonVar_list[1])

    return NativeContextLibrary(
      name: name,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      version,
    ]
  }
  static func == (lhs: NativeContextLibrary, rhs: NativeContextLibrary) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextOS: Hashable {
  var name: String? = nil
  var version: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextOS? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let version: String? = nilOrValue(pigeonVar_list[1])

    return NativeContextOS(
      name: name,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      version,
    ]
  }
  static func == (lhs: NativeContextOS, rhs: NativeContextOS) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextNetwork: Hashable {
  var cellular: Bool? = nil
  var wifi: Bool? = nil
  var bluetooth: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextNetwork? {
    let cellular: Bool? = nilOrValue(pigeonVar_list[0])
    let wifi: Bool? = nilOrValue(pigeonVar_list[1])
    let bluetooth: Bool? = nilOrValue(pigeonVar_list[2])

    return NativeContextNetwork(
      cellular: cellular,
      wifi: wifi,
      bluetooth: bluetooth
    )
  }
  func toList() -> [Any?] {
    return [
      cellular,
      wifi,
      bluetooth,
    ]
  }
  static func == (lhs: NativeContextNetwork, rhs: NativeContextNetwork) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeContextScreen: Hashable {
  var height: Int64? = nil
  var width: Int64? = nil
  var density: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeContextScreen? {
    let height: Int64? = nilOrValue(pigeonVar_list[0])
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let density: Double? = nilOrValue(pigeonVar_list[2])

    return NativeContextScreen(
      height: height,
      width: width,
      density: density
    )
  }
  func toList() -> [Any?] {
    return [
      height,
      width,
      density,
    ]
  }
  static func == (lhs: NativeContextScreen, rhs: NativeContextScreen) -> Bool {
    return deepEqualsContext(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashContext(value: toList(), hasher: &hasher)
  }
}

private class ContextPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeContext.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeContextApp.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeContextDevice.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeContextLibrary.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeContextOS.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeContextNetwork.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeContextScreen.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ContextPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeContext {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextApp {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextDevice {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextLibrary {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextOS {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextNetwork {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeContextScreen {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ContextPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ContextPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ContextPigeonCodecWriter(data: data)
  }
}

class ContextPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ContextPigeonCodec(readerWriter: ContextPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeContextApi {
  func getContext(collectDeviceId: Bool, completion: @escaping (Result<NativeContext, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeContextApiSetup {
  static var codec: FlutterStandardMessageCodec { ContextPigeonCodec.shared }
  /// Sets up an instance of `NativeContextApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeContextApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getContextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hightouch_events.NativeContextApi.getContext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let collectDeviceIdArg = args[0] as! Bool
        api.getContext(collectDeviceId: collectDeviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getContextChannel.setMessageHandler(nil)
    }
  }
}
