name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "13.0.13+5"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3

      - name: Get dependencies
        run: cd packages/core && flutter pub get

      - name: Analyze Dart code
        run: cd packages/core && flutter analyze

      - name: Run unit tests
        run: cd packages/core && flutter test
